- recipe:
    name: "Fresh Peach Cobbler I"
    difficulty: 1
    instructions: "Peaches!!"
    favorite: true
    remote_photo_url: "http://4.bp.blogspot.com/-qEDAjrCdmJk/TjrFmh_rMOI/AAAAAAAAA0g/ydwQKoXaD7c/s1600/PeachCobbler.jpg"
    description: "Best dessert in planet earth!"

- recipe:
    name: "New York Cheesecake"
    difficulty: 2
    instructions: "Enjoy!"
    favorite: true
    remote_photo_url: "http://www.cookingwithsugar.com/wp-content/uploads/2011/07/Homemade-Cheesecake-BEAUTY-e1309972389696.jpg"
    description: "This cake is easy to make and it is so delicious. Everyone that is tried it has said it tasted just like the ones in a deli! You will love it!"

- recipe:
    name: "Chocolate Chip Cookies"
    difficulty: 2
    instructions: "Mmmmmm Chocolate"
    favorite: false
    remote_photo_url: "http://upload.wikimedia.org/wikipedia/commons/b/b9/Chocolate_Chip_Cookies_-_kimberlykv.jpg"
    description: "Everybody wants this recipe when I take them in for a carry-in. To make them award winning my daughter Tegan made them for a cookie baking contest and won a red ribbon! You can use any flavor pudding you like for this recipe."

- recipe:
    name: "Blueberry Cobbler"
    difficulty: 3
    instructions: ""
    favorite: false
    remote_photo_url: "http://southernhillfarms.com/wp-content/uploads/2014/05/blueberry-cobbler-6-550.jpg"
    description: "I have tinkered and tinkered and this is the very best blueberry cobbler recipe I have found."

- recipe:
    name: "Tiramisu"
    difficulty: 2
    instructions: ""
    favorite: false
    remote_photo_url: "http://chocolatechillimango.com/wp-content/uploads/2011/06/tiramisu_0646_wm.jpg"
    description: "Mascarpone custard layered with whipped cream and rum and coffee soaked ladyfingers."

- recipe:
    name: "Apple Pie"
    difficulty: 1
    instructions: "Remember apples..."
    favorite: false
    remote_photo_url: "http://www.foodpost.ca/wp-content/uploads/2014/09/Apple_Pie.jpg"
    description: "This is THE American Apple Pie."

- recipe:
    name: "Peach Cobbler"
    difficulty: 1
    instructions: ""
    favorite: false
    remote_photo_url: "http://www.urbansacredgarden.com/wp-content/uploads/2012/07/Summer-Peach-Cobbler-with-Biscuit-Topping-2.jpg"
    description: "I have been experimenting with cobbler for some time and this recipe is the final result. Loved by all. Use fresh Georgia peaches of course!"

- recipe:
    name: "Strawberries and Cream Cake"
    difficulty: 1
    instructions: "eeeee"
    favorite: true
    remote_photo_url: "http://farm8.staticflickr.com/7122/6981134930_7e06e69bb1_b.jpg"
    description: "Makes an elegant presentation without too much fuss."

- recipe:
    name: "Black Magic Cake"
    difficulty: 1
    instructions: ""
    favorite: false
    remote_photo_url: "http://4.bp.blogspot.com/-9ef3eIZXOPs/TpXT6yJvayI/AAAAAAAAAI0/4YcH7Fx5tXo/s640/IMG_4200.JPG"
    description: "A simple dessert that is great served with ice cream."

- recipe:
    name: "Apple Crisp II"
    difficulty: 1
    instructions: ""
    favorite: false
    remote_photo_url: "http://3.bp.blogspot.com/_UIXOn06Pz70/SRJfH3RjoDI/AAAAAAAAFRQ/DCihBHoAVfc/s800/VanillaAppleCrispwithCaramelSauce500.jpg"
    description: "Sweet as heaven."

- recipe:
    name: "Best Brownies"
    difficulty: 1
    instructions: "The best!"
    favorite: true
    remote_photo_url: "http://a.dilcdn.com/bl/wp-content/uploads/sites/8/2011/8/bellalimentos-nutella-brownies.jpg"
    description: "These brownies always turn out!"

- recipe:
    name: "Carrot Cake"
    difficulty: 1
    instructions: "Carrots make this cake healthy!"
    favorite: false
    remote_photo_url: "http://www.villageinn.com/i/pies/profile/carrotcake_main1.jpg"
    description: "My Grandfather (Sam was famous for this cake. Everyone who knew him knows of his famous carrot cake."

- recipe:
    name: "Juicy Peach Crisp"
    difficulty: 1
    instructions: "Juicy and crispy..."
    favorite: false
    remote_photo_url: "http://www.the-baker-chick.com/wp-content/uploads/2013/07/peach.jpg"
    description: "This recipe takes the simplicity of fresh peaches and turns them into a scrumptious dessert!"

- recipe:
    name: "Triple Berry Sorbet"
    difficulty: 1
    instructions: "Tripple!"
    favorite: false
    remote_photo_url: "http://comfybelly.com/wp-content/uploads/2009/05/Strawberry-Sorbet.jpg"
    description: "This tart refreshing sorbet makes a great light dessert!"

- recipe:
    name: "Country Apple Dumplings"
    difficulty: 1
    instructions: ""
    favorite: false
    remote_photo_url: "http://2.bp.blogspot.com/-VkaNkGLl6H8/TnESsVDzaKI/AAAAAAAAGGs/4QOXqM9QqSE/s640/Apple-Dumpling-6.jpg"
    description: "Oh my Goodness!! Who knew that fresh apples, crescent roll dough, and citrus soda could make such a wonderful treat!"