- recipe:
    name: "Fresh Peach Cobbler I"
    difficulty: 1
    instructions: "Peaches!!"
    favorite: true
    photo: "PeachCobbler.jpg"
    description: "Best dessert in planet earth!"

- recipe:
    name: "New York Cheesecake"
    difficulty: 2
    instructions: "Enjoy!"
    favorite: true
    photo: "Homemade-Cheesecake-BEAUTY-e1309972389696.jpg"
    description: "This cake is easy to make and it is so delicious. Everyone that is tried it has said it tasted just like the ones in a deli! You will love it!"

- recipe:
    name: "Chocolate Chip Cookies"
    difficulty: 2
    instructions: "Mmmmmm Chocolate"
    favorite: false
    photo: "Chocolate_Chip_Cookies_-_kimberlykv.jpg"
    description: "Everybody wants this recipe when I take them in for a carry-in. To make them award winning my daughter Tegan made them for a cookie baking contest and won a red ribbon! You can use any flavor pudding you like for this recipe."

- recipe:
    name: "Blueberry Cobbler"
    difficulty: 3
    instructions: ""
    favorite: false
    photo: "blueberry-cobbler-6-550.jpg"
    description: "I have tinkered and tinkered and this is the very best blueberry cobbler recipe I have found."

- recipe:
    name: "Tiramisu"
    difficulty: 2
    instructions: ""
    favorite: false
    photo: "tiramisu_0646_wm.jpg"
    description: "Mascarpone custard layered with whipped cream and rum and coffee soaked ladyfingers."

- recipe:
    name: "Apple Pie"
    difficulty: 1
    instructions: "Remember apples..."
    favorite: false
    photo: "Apple_Pie.jpg"
    description: "This is THE American Apple Pie."

- recipe:
    name: "Peach Cobbler"
    difficulty: 1
    instructions: ""
    favorite: false
    photo: "Summer-Peach-Cobbler-with-Biscuit-Topping-2.jpg"
    description: "I have been experimenting with cobbler for some time and this recipe is the final result. Loved by all. Use fresh Georgia peaches of course!"

- recipe:
    name: "Strawberries and Cream Cake"
    difficulty: 1
    instructions: "eeeee"
    favorite: true
    photo: "6981134930_7e06e69bb1_b.jpg"
    description: "Makes an elegant presentation without too much fuss."

- recipe:
    name: "Black Magic Cake"
    difficulty: 1
    instructions: ""
    favorite: false
    photo: "IMG_4200.JPG"
    description: "A simple dessert that is great served with ice cream."

- recipe:
    name: "Apple Crisp II"
    difficulty: 1
    instructions: ""
    favorite: false
    photo: "VanillaAppleCrispwithCaramelSauce500.jpg"
    description: "Sweet as heaven."

- recipe:
    name: "Best Brownies"
    difficulty: 1
    instructions: "The best!"
    favorite: true
    photo: "bellalimentos-nutella-brownies.jpg"
    description: "These brownies always turn out!"

- recipe:
    name: "Carrot Cake"
    difficulty: 1
    instructions: "Carrots make this cake healthy!"
    favorite: false
    photo: "carrotcake_main1.jpg"
    description: "My Grandfather (Sam was famous for this cake. Everyone who knew him knows of his famous carrot cake."

- recipe:
    name: "Juicy Peach Crisp"
    difficulty: 1
    instructions: "Juicy and crispy..."
    favorite: false
    photo: "peach.jpg"
    description: "This recipe takes the simplicity of fresh peaches and turns them into a scrumptious dessert!"

- recipe:
    name: "Triple Berry Sorbet"
    difficulty: 1
    instructions: "Tripple!"
    favorite: false
    photo: "Strawberry-Sorbet.jpg"
    description: "This tart refreshing sorbet makes a great light dessert!"

- recipe:
    name: "Country Apple Dumplings"
    difficulty: 1
    instructions: ""
    favorite: false
    photo: "Apple-Dumpling-6.jpg"
    description: "Oh my Goodness!! Who knew that fresh apples, crescent roll dough, and citrus soda could make such a wonderful treat!"
